### PR TITLE
Added message length socket server/client pair

### PR DESCRIPTION
**Pull request by aewens**
In response to issue #5 for hacktoberfest

### CODE REVIEW

**Review by shauryauppal — CHANGES_REQUESTED** [review]
Almost Perfect but can you add a link make a Markdown what this Message length thing does?

**Comment by aewens** [comment]
Sure thing!

**Comment by shauryauppal** [comment]
@aewens write_sock variable unused. Please check the issues. White Spaces are not a problem would have merged.

**Comment by shauryauppal** [comment]
@aewens write_sock variable unused. Please check the issues. White Spaces are not a problem would have merged.

**Comment by shauryauppal** [comment]
@aewens only whitespace problem, be careful next time. Merging now. 👍  Nice Work

**Comment by aewens** [comment]
@shauryauppal sorry about all the changes, I'm not very used to linting. Thank you for being patient with me!

**Comment by shauryauppal** [comment]
@aewens Even I am not used to it. Try to adopt it now. I know efforts are being put up by you that is more important than just irritating you for just white spaces.

**Pull request merged**
